# Generated by Django 4.1.5 on 2023-01-22 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idNum', models.IntegerField()),
                ('ch1', models.FloatField()),
                ('ch2', models.FloatField()),
                ('ch3', models.FloatField()),
                ('ch4', models.FloatField()),
                ('ch5', models.FloatField()),
                ('ch6', models.FloatField()),
                ('ch7', models.FloatField()),
                ('ch8', models.FloatField()),
                ('ch9', models.FloatField()),
                ('ch10', models.FloatField()),
                ('ch11', models.FloatField()),
                ('ch12', models.FloatField()),
                ('ch13', models.FloatField()),
                ('ch14', models.FloatField()),
                ('userId', models.IntegerField()),
            ],
            options={
                'ordering': ['idNum'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampling_rate', models.IntegerField(default=128)),
            ],
        ),
        migrations.CreateModel(
            name='EEGData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_num', models.IntegerField()),
                ('AF3', models.FloatField()),
                ('AF4', models.FloatField()),
                ('F3', models.FloatField()),
                ('F4', models.FloatField()),
                ('F7', models.FloatField()),
                ('F8', models.FloatField()),
                ('FC5', models.FloatField()),
                ('FC6', models.FloatField()),
                ('O1', models.FloatField()),
                ('O2', models.FloatField()),
                ('P7', models.FloatField()),
                ('P8', models.FloatField()),
                ('T7', models.FloatField()),
                ('T8', models.FloatField()),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.session')),
            ],
            options={
                'ordering': ['session_id', 'row_num'],
            },
        ),
    ]
