version: '3'
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile-backend
    image: soundfield-backend
    container_name: django
    depends_on:
      - db
    ports:
      - "8000:8000"

  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes: 
      - ./db:/var/lib/postgresql/data
  frontend:
    build: .
    ports:
      - "8080:80"