version: '3'
services:
  django:
    build: ./rest
    command: python manage.py runserver 0.0.0.0:8000 & python manage.py makemigrations restApp & python manage.py migrate
    volumes:
      - ./rest:/app
    depends_on:
      - db
    ports:
      - "8000:8000"
  db:
    image: postgres
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes: 
      - ./db:/var/lib/postgresql/data
  frontend:
    build: ./frontend
    ports:
      - "8080:80"