# Generated by Django 4.1.3 on 2022-12-03 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='userId',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
